name: "Modify Deployment Type"
description: "Change the deployment type in the akumina.sitedeployer.config.json file"
inputs: 
    deployment_type:
        type: string
        # Documentation: https://akumina.github.io/docs/Site-Deployer-Version-6-0
        description: Akumina code deployment type
        required: true

runs:
  using: "composite"
  steps:

    - name: Modify deployment type
      working-directory: site
      shell: pwsh
      run: |
          $deployment_type = $env:DEPLOYMENT_TYPE

          # If no string is provided, assume "all" and set everything to false
          if ([string]::IsNullOrWhiteSpace($deployment_type)) {
              Write-Host "You must provide a deployment type to proceed."
              exit 1
          }

          # Read and parse the JSON file
          $jsonPath = "akumina.sitedeployer.config.json"
          $json = Get-Content -Raw -Path $jsonPath | ConvertFrom-Json

          # Set all options to false
          $json.Options.PSObject.Properties | ForEach-Object { $_.Value = $false }

          # Split the input on commas and update the JSON file accordingly
          $deployment_types = $deployment_type -split ","
          foreach ($dt in $deployment_types) {
              if ($json.Options.PSObject.Properties.Name -contains $dt) {
                  $json.Options.$dt = $true
              } else {
                  Write-Host "Warning: Deployment type '$dt' not found in JSON options."
              }
          }

          # Save the updated JSON (preserving formatting)
          $json | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonPath -Encoding UTF8
      env:
          DEPLOYMENT_TYPE: ${{ inputs.deployment_type }}