name: "Setup"
description: "Setup an Akumina deployment environment"

runs:
  using: "composite"
  steps:

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version-file: "site/.nvmrc"
          cache: 'npm'
          cache-dependency-path: "site/package-lock.json"
    
    - name: Run NPM
      working-directory: site
      shell: pwsh
      run: npm ci

    - name: Install Akumina SiteDeployer
      working-directory: site
      shell: pwsh
      run: |
          Invoke-WebRequest -Uri "https://github.com/akumina/SiteDeployer/releases/download/6.0.2301.1508/6.0.2301.1508-Akumina.SiteDeployer.zip" -OutFile "sd.zip"
          $ExtractPath = "tools"
          if (-not (Test-Path -Path $ExtractPath)) {
              New-Item -ItemType Directory -Path $ExtractPath | Out-Null
          }
          Expand-Archive -Path "sd.zip" -DestinationPath $ExtractPath -Force
          Remove-Item -Path "sd.zip"