name: Deploy Site
on:
  push:
  workflow_dispatch:
    inputs:
      deploymentType: 
        type: choice
        description: Which Akumina code to deploy
        options:
        - CSS
        - JS
        - All
      environment:
        type: environment

jobs:
  build:
    name: Deploy Site
    runs-on: windows-latest
    steps:

      ## Checkout the code
      - name: Checkout branch
        uses: actions/checkout@v3

      ## Setup node and npm caching
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com
          scope: "@nciocpl"
      - name: Run NPM
        run: npm install

      ## Deploy the code
      - name: Deploy Akumina
        run: npm run deploy
        env:
          spurl: ${{ secrets.spurl }}
          centralspurl: ${{ secrets.centralspurl }}
          spdirectory: DigitalWorkplace
          assetdirectory: myNCI
          envdir: ${{ github.workspace }}/build/
          ml: false
          clientid: ${{ secrets.clientid }}
          clientsecret: ${{ secrets.clientsecret }}