name: Deploy Delivery Site
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      deployment_type:
        type: string
        description: Which Akumina code to deploy
        required: true
jobs:
  deploy:
    name: Deploy to SharePoint
    runs-on: windows-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        working-directory: site

    steps:
      # Checkout the code
      - name: Checkout branch
        uses: actions/checkout@v3

      # Sets up our deployment 
      - uses: "./.github/workflows/composite/setup"
        with:
          deployment_type: ${{ inputs.deployment_type }}

      # Runs site deployer
      # We have chosen to use the tools/deploy.js script which reads from akumina.sitedeployer.config.json
      - name: Deploy to Delivery
        run: npm run deploy
        env:
          assetdirectory: Delivery
          clientid: ${{ secrets.client_id}}
          clientsecret: ${{ secrets.client_secret }}
          spurl: ${{ vars.delivery_sp_url }}
          spdirectory: DigitalWorkplace
          langid: 1033
          appmanagerurl: ${{ vars.appmanager_url }}
          akquerykey: ${{ secrets.ak_query_key }}
          ml: true
          envdir: ${{ github.workspace }}\site\build\
        
      - name: Deploy to Delivery with Central
        run: npm run deploy
        env:
          assetdirectory: Delivery
          clientid: ${{ secrets.client_id}}
          clientsecret: ${{ secrets.client_secret }}
          spurl: ${{ vars.delivery_sp_url }}
          centralspurl: ${{ vars.central_sp_url }}
          spdirectory: DigitalWorkplace
          langid: 1033
          appmanagerurl: ${{ vars.appmanager_url }}
          akquerykey: ${{ secrets.ak_query_key }}
          ml: true
          envdir: ${{ github.workspace }}\site\build\
      
      # Stores an artifact copy on the workflow run
      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          path: site/build
  