name: Deploy Site
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        working-directory: site

    steps:

      # Checkout the code
      - name: Checkout branch
        uses: actions/checkout@v3