name: Lint Code
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
      - 'prototype/**'
    tags:
      - '*'

jobs:
  deploy:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site

    steps:

      # Checkout the code
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version-file: "site/.nvmrc"
            cache: 'npm'
            cache-dependency-path: "site/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint